### PR TITLE
stpm: correct argument parsing to for the console script

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Review by kgugala — CHANGES_REQUESTED** [review]
In general LGTM. One question - why do you change every `'` to `"`? If we want to go with `"` can you extract this formatting change into a separate commit?

**Comment by acomodi** [comment]
@kgugala Sure, no problem, I wanted to get the script formatted but forgot to separate the two commits (I used black to do so). Probably it will be worth adding the format check to CI as well.

**Comment by kgugala** [comment]
> @kgugala Sure, no problem, I wanted to get the script formatted but forgot to separate the two commits (I used black to do so). Probably it will be worth adding the format check to CI as well.

indeed. See #3 and #4

**Review by kgugala — APPROVED** [review]

**Comment by kgugala** [comment]
LGTM

**Pull request merged**
